spring:
  datasource:
        url: jdbc:mysql://localhost:3306/shop
        username: root
        password: gby19951218
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
  thymeleaf:
        mode: HTML5
#mynatis配置 
mybatis:
  type-aliases-package: com.shop.springboot.vo
  #mapper加载路径
  mapper-locations: classpath:mapper/*Mapper.xml
  
server:
    port: 8080
